import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import AppNavbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--font-tajawal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "v0.app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" className={`${tajawal.variable}`}>
      <body className="antialiased font-tajawal ">
        <AppNavbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
